In [1]:
from PIL import Image
import os, glob
import numpy as np
 


In [6]:
image = Image.open('./mask.png')
image = image.convert("RGB")
data = np.asarray(image)
data

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ..., 
       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255,

In [7]:
data2=data[:,:,0]
data2


array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ..., 
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [12]:
data3 = np.where(data2 < 240, 0, 1)
data3
data3[28,79]

0

In [15]:
data4=np.where(data3==0,1.4,1)
data4
data4[28,79]

1.3999999999999999

In [16]:
np.save('./fibro_mask.npy',data4)

In [11]:
print(list(zip(*np.where(data3 ==0))))
# [(0, 0), (0, 1), (0, 2), (1, 0)]

[(28, 79), (28, 80), (28, 81), (28, 82), (28, 83), (28, 84), (29, 77), (29, 78), (29, 79), (29, 80), (29, 81), (29, 82), (29, 83), (29, 84), (29, 85), (29, 86), (30, 75), (30, 76), (30, 77), (30, 78), (30, 79), (30, 80), (30, 81), (30, 82), (30, 83), (30, 84), (30, 85), (30, 86), (30, 87), (31, 74), (31, 75), (31, 76), (31, 77), (31, 78), (31, 79), (31, 80), (31, 81), (31, 82), (31, 83), (31, 84), (31, 85), (31, 86), (31, 87), (31, 88), (32, 74), (32, 75), (32, 76), (32, 77), (32, 78), (32, 79), (32, 80), (32, 81), (32, 82), (32, 83), (32, 84), (32, 85), (32, 86), (32, 87), (32, 88), (32, 89), (33, 73), (33, 74), (33, 75), (33, 76), (33, 77), (33, 78), (33, 79), (33, 80), (33, 81), (33, 82), (33, 83), (33, 84), (33, 85), (33, 86), (33, 87), (33, 88), (33, 89), (33, 90), (34, 72), (34, 73), (34, 74), (34, 75), (34, 76), (34, 77), (34, 78), (34, 79), (34, 80), (34, 81), (34, 82), (34, 83), (34, 84), (34, 85), (34, 86), (34, 87), (34, 88), (34, 89), (34, 90), (35, 72), (35, 73), (35, 74),

In [2]:
image = Image.open('./mask3.png')
image = image.convert("RGB")
data = np.asarray(image)
data

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ..., 
       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ..., 
        [255, 255, 255],
        [255, 255, 255],
        [255, 255,

In [3]:
data2=data[:,:,0]
data2
data3 = np.where(data2 < 240, , 1)
data3
data3[28,79]

1